kind: ServiceAccount
apiVersion: v1
metadata:
  name: sa-nfs-dynamic-provisioner
---
kind: ClusterRole 
apiVersion: rbac.authorization.k8s.io/v1 # auth API
metadata:
  name: clusterrole-nfs-dynamic-provisioner
rules:
  - apiGroups: [""] # rules on persistentvolumes
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrolebinding-nfs-dynamic-provisioner
subjects:
  - kind: ServiceAccount
    name: sa-nfs-dynamic-provisioner 
    namespace: default
roleRef: 
  kind: ClusterRole
  name: clusterrole-nfs-dynamic-provisioner 
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-nfs-dynamic-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-nfs-dynamic-provisioner
subjects:
  - kind: ServiceAccount
    name: sa-nfs-dynamic-provisioner 
    namespace: default
roleRef:
  kind: Role
  name: role-nfs-dynamic-provisioner
  apiGroup: rbac.authorization.k8s.io
